spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.56.56:3306/shopping_pms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 # nacos 注册中心的服务地址
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss # 指定日期格式化形式
    time-zone: Asia/Shanghai
  application:
    name: shopping-product # 当前服务的名字
  thymeleaf:
    cache: false # 关闭 thymeleaf 缓存，便于调试
  redis:
    host: 192.168.56.56
    port: 6379
  cache:
    type: redis # 使用 Redis 作为缓存组件
    redis:
      time-to-live: 3600000 # 设置缓存存活时间 1h
      use-key-prefix: true # 设置是否启用缓存前缀，默认是true，并且不指定缓存的前缀，默认使用缓存的名字作为前缀，
                           # 这样的好处是：存储同一类型的数据，都可以指定成同一个分区，使用 allEntries=true 可以直接删除某个分区下的所有数据
      cache-null-values: true # 是否缓存空值，设置为 true 可以防止缓存穿透
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml  # 配置映射文件地址
  global-config:
    db-config:
      id-type: auto # 配置主键自增
      logic-delete-value: 1 # 逻辑已删除值
      logic-not-delete-value: 0 # 逻辑未删除值
server:
  port: 10000

# 开启 SQL 调试
logging:
  level:
    cn.parzulpan.shopping: debug

# 线程池相关配置
shopping:
  thread:
    core-size: 20
    max-size: 200
    keep-alive-time: 10